# fly.toml app configuration file generated for employeemanager on 2023-08-27T20:17:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "employeemanager"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "flyio/builder"

[env]
  PORT = "3000" # add this

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    internal_port = 8000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
    internal_port = 8000

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
